# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('systemName', models.CharField(max_length=255)),
                ('hostName', models.CharField(max_length=255)),
                ('dns', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
                ('domainRole', models.CharField(max_length=255)),
                ('ipAddress', models.CharField(max_length=255)),
                ('dynamicIp', models.CharField(max_length=255)),
                ('assetType', models.CharField(max_length=255)),
                ('hardware', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serialNumber', models.CharField(max_length=255)),
                ('warrantyStatus', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('operatingSystem', models.CharField(max_length=255)),
                ('osVersion', models.CharField(max_length=255)),
                ('lastBoot', models.CharField(max_length=255)),
                ('hardwareAgent', models.CharField(max_length=255)),
                ('businessUnit', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
