# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180102_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='country',
            field=models.CharField(choices=[('ARGENTINA', 'ARGENTINA'), ('BOLIVIA', 'BOLIVIA'), ('BRASIL', 'BRASIL'), ('CHILE', 'CHILE'), ('COLOMBIA', 'COLOMBIA'), ('ECUADOR', 'ECUADOR'), ('PARAGUAY', 'PARAGUAY'), ('PERU', 'PERU'), ('URUGUAY', 'URUGUAY'), ('Venezuela', 'VENEZUELA')], max_length=255),
        ),
    ]
